In [8]:
import pandas as pd

data_frame = "data_scaling_skewed_data.csv"
df = pd.read_csv(data_frame)
df.head()

,Student_ID,Study_Hours,Age,Attendance,Family_Income,Internet_Usage_Hours,Exam_Score
0,1,4.79,25,68.22,26401.83,5.13,68.46
1,2,2.99,25,72.62,29899.43,10.14,58.53
2,3,2.76,24,87.15,84956.82,6.63,50.72
3,4,2.76,20,87.14,15797.16,0.99,72.44
4,5,9.30,18,87.15,44019.48,2.10,60.92

In [9]:
df.isna().sum()

Student_ID              0
Study_Hours             0
Age                     0
Attendance              3
Family_Income           0
Internet_Usage_Hours    2
Exam_Score              0
dtype: int64

In [10]:
df = df.dropna() 
df.shape

(95, 7)

In [11]:
import matplotlib.pyplot as plt
import plotly.express as px
import plotly.graph_objects as go
fig = go.Figure()
fig.add_trace(go.Scatter3d(x = df["Study_Hours"], y=df["Attendance"],z=df["Exam_Score"]))
fig.show()

In [12]:
df.shape

(95, 7)

In [13]:
import numpy as np
a= np.ones(df.shape[0])

In [14]:
x = df[["Study_Hours","Attendance"]].values
X = np.c_[np.ones(df.shape[0]),x]
X

array([[  1.  ,   4.79,  68.22],
       [  1.  ,   2.99,  72.62],
       [  1.  ,   2.76,  87.15],
       [  1.  ,   2.76,  87.14],
       [  1.  ,   9.3 ,  87.15],
       [  1.  ,   5.73, 100.  ],
       [  1.  ,   2.26,  87.71],
       [  1.  ,   4.  ,  91.54],
       [  1.  ,   0.43,  88.51],
       [  1.  ,   1.34,  78.85],
       [  1.  ,   4.21,  89.59],
       [  1.  ,   8.73,  74.27],
       [  1.  ,   2.78,  79.63],
       [  1.  ,   2.12,  77.15],
       [  1.  ,   2.01, 100.  ],
       [  1.  ,   2.64,  63.33],
       [  1.  ,   3.3 ,  88.86],
       [  1.  ,   1.28,  65.87],
       [  1.  ,   5.94,  77.28],
       [  1.  ,   1.07,  92.89],
       [  1.  ,   0.95,  82.64],
       [  1.  ,   3.87,  71.22],
       [  1.  ,   3.8 ,  88.8 ],
       [  1.  ,   3.04,  74.7 ],
       [  1.  ,   2.61,  84.16],
       [  1.  ,   2.28,  82.46],
       [  1.  ,   6.88,  75.48],
       [  1.  ,   4.24, 100.  ],
       [  1.  ,   2.43,  88.34],
       [  1.  ,   1.87,  61.75],
       [  1.  ,   5.18,  83.86],
       [  1.  ,   6.77,  75.38],
       [  1.  ,   6.36,  90.52],
       [  1.  ,   1.6 ,  74.07],
       [  1.  ,   2.6 ,  80.85],
       [  1.  ,   2.24,  87.05],
       [  1.  ,   2.88,  90.66],
       [  1.  ,   5.9 ,  70.  ],
       [  1.  ,   8.2 ,  78.65],
       [  1.  ,   4.36,  77.25],
       [  1.  ,   1.93,  75.47],
       [  1.  ,   3.24,  99.65],
       [  1.  ,   9.23,  86.05],
       [  1.  ,   3.56,  69.39],
       [  1.  ,   2.62,  91.18],
       [  1.  ,   2.8 , 100.  ],
       [  1.  ,   4.34,  92.32],
       [  1.  ,   1.65,  66.81],
       [  1.  ,   6.3 ,  94.67],
       [  1.  ,   4.26,  74.92],
       [  1.  ,   3.59,  86.44],
       [  1.  ,   6.51,  89.75],
       [  1.  ,   1.83,  72.73],
       [  1.  ,   2.56,  81.4 ],
       [  1.  ,   4.16,  49.59],
       [  1.  ,   4.05,  71.76],
       [  1.  ,   0.85,  79.47],
       [  1.  ,   2.36,  69.52],
       [  1.  ,   2.93,  98.32],
       [  1.  ,   4.49,  67.7 ],
       [  1.  ,   4.04,  77.6 ],
       [  1.  ,   3.14,  83.31],
       [  1.  ,   0.43,  96.41],
       [  1.  ,   3.27,  67.64],
       [  1.  ,  14.6 ,  82.1 ],
       [  1.  ,   2.86,  72.18],
       [  1.  ,   4.17,  86.62],
       [  1.  ,   7.24,  83.99],
       [  1.  ,   5.68,  76.  ],
       [  1.  ,   8.43,  82.7 ],
       [  1.  ,   0.87,  78.15],
       [  1.  ,   1.37,  83.14],
       [  1.  ,   2.07,  88.62],
       [  1.  ,   0.72,  97.86],
       [  1.  ,   3.51,  69.62],
       [  1.  ,   1.48, 100.  ],
       [  1.  ,   9.15,  62.48],
       [  1.  ,   1.69,  80.48],
       [  1.  ,   2.57,  87.88],
       [  1.  ,   5.91,  84.81],
       [  1.  ,   1.06,  75.77],
       [  1.  ,   0.67,  79.92],
       [  1.  ,   3.83,  77.07],
       [  1.  ,   4.05,  76.11],
       [  1.  ,   5.79,  90.5 ],
       [  1.  ,   4.87,  85.57],
       [  1.  ,   4.16,  75.07],
       [  1.  ,   1.87,  91.  ],
       [  1.  ,   3.97,  85.07],
       [  1.  ,   4.15,  90.13],
       [  1.  ,   1.81,  88.3 ],
       [  1.  ,  10.84,  73.71],
       [  1.  ,   4.71,  76.4 ],
       [  1.  ,   1.4 ,  89.47],
       [  1.  ,   5.81,  88.1 ]])

In [15]:
Y = df["Exam_Score"].values
Y

array([68.46, 58.53, 50.72, 72.44, 60.92, 52.93, 62.24, 90.25, 80.58,
       69.9 , 87.76, 70.93, 59.66, 88.28, 57.55, 67.72, 59.49, 53.41,
       81.11, 92.91, 53.22, 76.76, 64.15, 62.89, 59.63, 70.58, 60.03,
       73.25, 69.4 , 67.13, 59.11, 63.08, 79.06, 76.01, 58.27, 71.19,
       79.02, 49.97, 76.52, 62.05, 76.85, 60.84, 48.34, 50.47, 70.58,
       73.12, 59.15, 77.66, 69.21, 55.47, 62.18, 70.57, 59.68, 65.39,
       82.08, 63.08, 80.03, 56.44, 76.36, 87.3 , 40.34, 60.44, 76.92,
       67.56, 62.75, 71.04, 68.13, 84.01, 73.05, 74.05, 65.06, 64.15,
       64.81, 74.73, 64.95, 73.48, 94.9 , 80.45, 66.09, 84.41, 65.1 ,
       45.54, 57.9 , 47.55, 65.78, 70.22, 90.12, 73.92, 67.37, 79.95,
       43.47, 72.83, 79.25, 52.26, 83.73])

In [16]:
def mlr(x,y):
  coff_b =np.linalg.inv(x.T @ x) @ x.T @ y
  return coff_b

In [17]:
b = mlr(X,Y)
print(b)

[6.50718439e+01 3.33586115e-01 2.12159375e-02]

In [18]:
b.shape

(3,)

In [19]:
y_pred = X @ b
y_pred

array([68.11707265, 67.60996777, 67.84151054, 67.84129838, 70.02316373,
       69.1048861 , 67.6865984 , 68.34829529, 67.09310856, 67.19172597,
       68.37697729, 69.55975837, 67.68863841, 67.41585605, 67.86394575,
       67.29611657, 68.05792629, 66.89632794, 68.69291308, 67.39952948,
       67.14203579, 67.87382124, 68.22344639, 67.67077623, 67.72803697,
       67.58188646, 68.96829534, 68.60784278, 67.75667409, 67.00573408,
       68.5789885 , 68.92947927, 69.11391826, 67.17704618, 67.65447635,
       67.66592416, 67.95600881, 68.52511761, 69.47588353, 68.16521054,
       67.31683191, 68.26683109, 69.97647517, 67.73158438, 67.88030871,
       68.12747878, 68.478263  , 67.03969778, 69.18194924, 68.08241879,
       68.1033237 , 69.14761991, 67.22534163, 67.65280167, 67.51166049,
       67.94532335, 67.04142266, 67.33403911, 68.1352022 , 68.00596453,
       68.06588856, 67.88680406, 67.26071447, 67.59771652, 71.68402966,
       67.55726656, 68.30062251, 69.26893397, 68.57902429, 69.63853289,
       67.02008934, 67.29274993, 67.64252355, 67.38821755, 67.71978474,
       67.68714511, 69.44972863, 67.34306309, 67.79361681, 68.84266151,
       67.03297677, 66.99092433, 67.98459103, 68.03761268, 68.92334986,
       68.51185606, 68.05224257, 67.62630025, 68.20102059, 68.36841873,
       67.54900206, 70.25174415, 68.26393213, 67.4370544 , 68.87910333])

In [20]:
compare = pd.DataFrame({
    "Actual":Y,
    "predict":y_pred
})
compare

    Actual    predict
0    68.46  68.117073
1    58.53  67.609968
2    50.72  67.841511
3    72.44  67.841298
4    60.92  70.023164
..     ...        ...
90   43.47  67.549002
91   72.83  70.251744
92   79.25  68.263932
93   52.26  67.437054
94   83.73  68.879103

[95 rows x 2 columns]